version: "3.9"  # optional since v1.27.0
services:
  mockbin:
    build: .
    environment:
      NODE_DEBUG: mockbin
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
